# DATA CLEANING & PREPARATION
- This notebook will be used to clean the data that will be used for this project.
- The data was obtained from ***https://ckan.africadatahub.org/dataset/kenya-femicide-data***
- In this notebook, we will clean standardize and normalize the data to prepare it for analysis in the EDA notebook.

In [1]:
# Importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("../Data/raw/kenya-femicide-data_2016_dec2023.xlsx")
df.head()

,url,title,author_name,medium,country_name,text,published_date,type of murder,name of victim,Age,...,Type of femicide,Murder Scene,Mode of killing,Circumstance,Status on article date,Court date (first appearance),verdict date,Verdict,Years of sentence,Days to verdict
0,http://www.standardmedia.co.ke/article/2000218...,Meru man who killed drunk wife sentenced to hang,Lydiah Nyawira,Standard Digital (Kenya),Kenya,"On August 12, 2005 at around 7pm, Joyce Gacher...",2016-10-05,Femicide,Dorcas Kaguri,Unknown,...,Intimate,home,blunt force,Argument,Unknown,2005-08-13 00:00:00,2016-06-24 00:00:00,Guilty,Death,4061
1,http://www.standardmedia.co.ke/article/2001300...,"Court: Kakamega man guilty of raping, killing ...",Jack Murima,Standard Digital (Kenya),Kenya,"Jack Murima - Sun, 28. October 2018 12:54 PM -...",2018-10-29,Femicide,Selina Ikambi Anasi,79,...,Non-intimate,Public Space,hacked,Unknown,Unknown,Unknown,2018-10-28 00:00:00,guilty,awaiting ruling,2817
2,http://www.standardmedia.co.ke/article/2001241...,My wife 'died from fall in fight over volume o...,Kamau Muthoni,Standard Digital (Kenya),Kenya,Former journalist Moses Dola Otieno yesterday ...,2017-05-25,Femicide,Wambui Kabiru,Unknown,...,Intimate,home,blunt force,Argument,Unknown,Unknown,2018-10-05 00:00:00,guilty,10,2714
3,http://www.nation.co.ke/news/Kabogo-cleared-Me...,Kabogo cleared in varsity student's murder case,ELISHA OTIENO,Daily Nation (Kenya),Kenya,Kiambu Governor Kabogo and five others adverse...,2016-10-07,Femicide,Mercy Keino,Unknown,...,Unknown,Public Space,Unknown,Unknown,Unknown,Unknown,2016-10-07 00:00:00,Not Guilty,Freed,1939
4,http://www.mediamaxnetwork.co.ke/news/pastor-t...,"Pastor to serve 25 years in jail for defiling,...",People Daily,MediaMax Network,Kenya,Musa Wekesa A pastor from Kitale has been sent...,2019-05-25,Femicide,Scholastica Mmbihi,Unknown,...,Unknown,home,stabbed,Argument,Unknown,Unknown,2019-05-25 00:00:00,guilty,25,2879

In [3]:
df.shape

(507, 24)

In [4]:
df.columns

Index(['url', 'title', 'author_name', 'medium', 'country_name', 'text',
       'published_date', 'type of murder', 'name of victim', 'Age',
       'date of murder', 'Location', 'name of suspect', 'suspect relationship',
       'Type of femicide', 'Murder Scene', 'Mode of killing', 'Circumstance',
       'Status on article date', 'Court date (first appearance)',
       'verdict date', 'Verdict', 'Years of sentence', 'Days to verdict'],
      dtype='object')

In [37]:
df.describe()

,url,title,author_name,medium,country_name,text,published_date,type of murder,name of victim,Age,...,Type of femicide,Murder Scene,Mode of killing,Circumstance,Status on article date,Court date (first appearance),verdict date,Verdict,Years of sentence,Days to verdict
count,507,507,507,507,507,507,507,507,507,507,...,507,507,507,507,507,507,507,507,507,507
unique,507,477,285,26,1,469,427,2,399,65,...,7,10,13,48,15,67,37,6,20,37
top,http://www.standardmedia.co.ke/article/2000218...,Femicide,Unknown,The Star (Kenya),Kenya,Femicide was committed,Unknown,Femicide,Unnamed,Unknown,...,Intimate,home,stabbed,Unknown,under investigation,Unknown,Unknown,Unknown,Unknown,#VALUE!
freq,1,28,43,188,507,39,28,493,103,195,...,311,256,143,218,274,440,471,469,471,471

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            507 non-null    object
 1   title                          479 non-null    object
 2   author_name                    473 non-null    object
 3   medium                         495 non-null    object
 4   country_name                   492 non-null    object
 5   text                           468 non-null    object
 6   published_date                 479 non-null    datetime64[ns]
 7   type of murder                 507 non-null    object
 8   name of victim                 507 non-null    object
 9   Age                            507 non-null    object
 10  date of murder                 507 non-null    object
 11  Location                       505 non-null    object
 12  name of suspect                468 non-null    object
 13  suspect relationship           505 non-null    object
 14  Type of femicide               448 non-null    object
 15  Murder Scene                   507 non-null    object
 16  Mode of killing                507 non-null    object
 17  Circumstance                   438 non-null    object
 18  Status on article date         436 non-null    object
 19  Court date (first appearance)  408 non-null    object
 20  verdict date                   507 non-null    object
 21  Verdict                        406 non-null    object
 22  Years of sentence              405 non-null    object
 23  Days to verdict                507 non-null    object
dtypes: datetime64[ns](1), object(23)
memory usage: 95.2+ KB

In [7]:
# Check the number of missing values in each column
for col in df.columns:
    print(f'{col}: {df[col].isna().sum()}')

url: 0
title: 28
author_name: 34
medium: 12
country_name: 15
text: 39
published_date: 28
type of murder: 0
name of victim: 0
Age: 0
date of murder: 0
Location: 2
name of suspect: 39
suspect relationship: 2
Type of femicide: 59
Murder Scene: 0
Mode of killing: 0
Circumstance: 69
Status on article date: 71
Court date (first appearance): 99
verdict date: 0
Verdict: 101
Years of sentence: 102
Days to verdict: 0

### Filling Na VAlues column by column
Since we only 507 records rather than droping the Na values its better to fill them while keeping the integrity of the data

In [10]:
# Filling Title column with Femicide
df['title'] = df['title'].fillna('Femicide')

#Checking if there is still missing values in that column
df['title'].isna().sum()

np.int64(0)

In [14]:
# Filling authour name with unknown
df['author_name'] = df['author_name'].fillna('Unknown')
df['author_name'].isna().sum()

np.int64(0)

In [ ]:
# Filling Medium with the most frequent value
df['medium'] = df['medium'].fillna(df['medium'].mode()[0])
df['medium'].isna().sum()

np.int64(0)

In [ ]:
#Filling country_name with kenya
df['country_name'] = df['country_name'].fillna('Kenya')
df['country_name'].isna().sum()

np.int64(0)

In [23]:
df['text'] = df['text'].fillna('Femicide was committed')
df['text'].isna().sum()

np.int64(0)

In [26]:
df['published_date'] =  pd.to_datetime(df['published_date'])
df['published_date'][299]

Timestamp('2020-09-15 00:00:00')

In [27]:
#Filling missing published dates with Unkown
df['published_date'] = df['published_date'].fillna('Unknown')
df['published_date'].isna().sum()

np.int64(0)

In [30]:
# Location with Uknown
df['Location'] = df['Location'].fillna('Unknown')
df['Location'].isna().sum()

np.int64(0)

In [31]:
df['name of suspect'] = df['name of suspect'].fillna('Unknown')
df['name of suspect'].isna().sum()

np.int64(0)

In [32]:
df['suspect relationship'] = df['suspect relationship'].fillna('Unknown')
df['suspect relationship'].isna().sum()

np.int64(0)

In [33]:
#Type of femicide
df['Type of femicide'] = df['Type of femicide'].fillna('Unknown')
df['Type of femicide'].isna().sum()

np.int64(0)

In [35]:
df[['Circumstance', 'Status on article date', 'Court date (first appearance)', 'verdict date', 'Verdict',
'Years of sentence', 'Days to verdict']] = df[['Circumstance', 'Status on article date', 'Court date (first appearance)', 'verdict date', 'Verdict',
'Years of sentence', 'Days to verdict']].fillna('Unknown')

#Checking the whole dataset for mising values in each column
for col in df.columns:
    print(f'{col}: {df[col].isna().sum()}')

url: 0
title: 0
author_name: 0
medium: 0
country_name: 0
text: 0
published_date: 0
type of murder: 0
name of victim: 0
Age: 0
date of murder: 0
Location: 0
name of suspect: 0
suspect relationship: 0
Type of femicide: 0
Murder Scene: 0
Mode of killing: 0
Circumstance: 0
Status on article date: 0
Court date (first appearance): 0
verdict date: 0
Verdict: 0
Years of sentence: 0
Days to verdict: 0

- Once Null values have been filled we can now proceed to checking the data types  of each column and validate them
- I find the best way for this is to use value_counts() method to see if the data types do match the expected values

In [40]:
# Check the top 5 values of each column
for col in df.columns:
    print(f'{col}:\n{df[col].value_counts().head()}')

url:
url
http://www.standardmedia.co.ke/article/2000218467/meru-man-who-killed-drunk-wife-sentenced-to-hang               1
http://www.standardmedia.co.ke/article/2001300764/court-kakamega-man-guilty-of-raping-killing-his-grandmother    1
http://www.standardmedia.co.ke/article/2001241021/my-wife-died-from-fall-in-fight-over-volume-of-radio           1
http://www.nation.co.ke/news/Kabogo-cleared-Mercy-Keino-murder-inquest/1056-3408370-1p17r1z/index.html           1
http://www.mediamaxnetwork.co.ke/news/pastor-to-serve-25-years-in-jail-for-defiling-killing-student-527203       1
Name: count, dtype: int64
title:
title
Femicide                                                                28
Muchatha killings puzzle as ruthless gang rape, kills, maims at will     2
Bungoma man murders, buries wife in shallow grave behind their house     2
Kisumu man arrested for killing wife after domestic quarrel              2
Pastor to serve 25 years in jail for defiling, killing student           1
Name: count, dtype: int64
author_name:
author_name
Unknown                          43
Cyrus Ombati                     14
CYRUS OMBATI CYRUS OMBATI        10
GEORGE MURAGE GEORGE MURAGE       8
CAROLYNE KUBWA CAROLYNE KUBWA     6
Name: count, dtype: int64
medium:
medium
The Star (Kenya)            188
Standard Digital (Kenya)     99
Daily Nation (Kenya)         99
Standard digital             32
Nairobi News                 12
Name: count, dtype: int64
country_name:
country_name
Kenya    507
Name: count, dtype: int64
text:
text
Femicide was committed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             39
A businessman who was found guilty of murdering his girlfriend in Buruburu Phase 5, Nairobi has been sentenced to 20 years imprisonment. Erastus Ngura Odhiambo is said to have pulled his girlfriend, the late Linda Wanjiku Irungu, out of her car and shot her dead at Waihura Court in December 2014.\n\nOn Friday (July 27, 2018), High Court Judge Stella Mutuku ruled that there was enough evidence proving Mr Odhiambo committed the offence.\n\n"I have with great care considered all evidence from defence and prosecution, and I find all the ingredients of murder proved beyond reasonable doubt. I find the accused guilty of the offence of murder as charged and convict him accordingly," Justice Stella Mutuku ruled.\n\nThe two are said to have been living together for more than two years, but on the fateful day the late was staying with her sister.\n\nIn her ruling, the Justice Mutuku said that the accused did not plead provocation or drunkenness in his defence. The judge said the gun recovered from Odhiambo was the same that was used to kill Wanjiku.\n\nOdhiambo was found guilty of multiple charges; having unlicenced firearm and being in possession of a gun that was used in the murder.\n\nThe death\n\nThe court heard that the accused had gone looking for Wanjiku on the night she was killed and found her inside her car preparing to drive out of Waihura Court.\n\nOdhiambo then blocked the car, moved to the driver's side and pulled Wanjiku out, leaving the vehicle to roll on towards the gate.\n\nA quarrel ensued between the two during which Odhiambo is reported to have assaulted Wanjiku before shooting her.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
11-year-old Jasmine Njoki, who was defiled and killed before her body was dumped in a thicket at Kasambara village in Gilgil, Nakuru County. Njoki, a Grade Six pupil, was killed on September 19 around 5pm as she was heading home from Nakuru Roots Academy, where she was a pupil.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
Peris is believed to have been raped before being killed on her way back home from church.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
A father who killed his wife nine years ago after he found her having sex with another man in the bush will continue serving his 20-year sentence. The appellate court threw out his appeal. Mdoe Kombe was sentenced and convicted in 2018 on the lesser offence of manslaughter after the High Court found that he indeed killed his wife Kwekwe Nyanje. Kombe had been charged with murdering Kwekwe on October 4, 2011, at about 4pm in Majugwani village, Mwereni location, Kwale county. Kombe had admitted to having killed his wife. However, he stated that it was because he had found her having sex with another man in a bush. He allegedly chased the man and his wife escaped to her parents' home, where he had found her and eventually stabbed her to death. The trial court in its judgment ruled that the husband was provoked into committing the offence. It convicted him of manslaughter rather than the murder he had been charged with, going ahead to sentence him to 20 years behind bars. He appealed, arguing that the judge erred in law by failing to see that nobody testified to have witnessed seeing him at the alleged scene of crime killing his wife, which he later withdrew and stuck to appealing the sentence. He challenged the sentence, arguing that counsel asserted that the sentence was harsh and excessive. Counsel also said after he was convicted, the appellant had stated in mitigation that he was a first offender, was now a single parent, and had shown remorse, and prayed for leniency. However, Justices DK Musinga, Gatembu Kairu and Agnes Murgor dismissed his arguments on sentence, ruling they had no jurisdiction to entertain appeals on the severity of the sentence. "Bearing this in mind, we are of the view that the learned judge took into account the facts of the case, and more particularly the appellant's probation report, and exercising of his discretion, sentenced the appellant to 20 years' imprisonment," the court ruled. "As such, we have no reason to interfere with the sentence imposed." During the trial of the case at the High Court, Kombe's father-in-law had testified that his late daughter and Kombe had an understanding that she went back home. Kombe allegedly followed her to their home to resolve the misunderstanding, but when his father-in-law went to call the elders to settle the dispute, he was called by his wife and told that his daughter had been stabbed. "On his return, he found that the appellant had left the home and his daughter was lying in a pool of blood with a huge cut wound on her neck," court papers read.     1
Name: count, dtype: int64
published_date:
published_date
Unknown                28
2020-07-29 00:00:00     3
2018-05-15 00:00:00     3
2021-12-07 00:00:00     3
2018-07-14 00:00:00     2
Name: count, dtype: int64
type of murder:
type of murder
Femicide    493
femicide     14
Name: count, dtype: int64
name of victim:
name of victim
Unnamed             103
Unknown               3
Margaret Wanjiru      2
Milca Mwangi          2
Lucy Atieno           2
Name: count, dtype: int64
Age:
Age
Unknown    195
22          22
25          19
24          15
26          15
Name: count, dtype: int64
date of murder:
date of murder
Unknown                14
2018-05-14 00:00:00     3
2017-06-02 00:00:00     3
2019-09-12 00:00:00     3
2017-09-16 00:00:00     3
Name: count, dtype: int64
Location:
Location
Naivasha, Nakuru county             6
Nakuru County                       4
Unknown                             4
Eldoret town, Uasin Gishu county    3
Gilgil, Nakuru County               3
Name: count, dtype: int64
name of suspect:
name of suspect
Unknown                     193
Unknown assailant             3
Jared Nyongesa                2
Bernard Kiiru (deceased)      2
Paul Ochieng                  2
Name: count, dtype: int64
suspect relationship:
suspect relationship
husband                          129
Boyfriend                        117
Husband                           90
Stranger/Unknown Relationship     89
Friend/Known to victim            22
Name: count, dtype: int64
Type of femicide:
Type of femicide
Intimate        311
Unknown         109
Non-intimate     52
INtimate         15
non-intimate     12
Name: count, dtype: int64
Murder Scene:
Murder Scene
home            256
Public Space    107
Home             83
Unknown          38
Other            11
Name: count, dtype: int64
Mode of killing:
Mode of killing
stabbed        143
blunt force     74
hacked          67
Unknown         66
strangled       54
Name: count, dtype: int64
Circumstance:
Circumstance
Unknown     218
Argument    158
jealousy     43
breakup      13
Jealousy      9
Name: count, dtype: int64
Status on article date:
Status on article date
under investigation    274
Unknown                130
ongoing hearings        40
both are dead           27
Under Investigation     15
Name: count, dtype: int64
Court date (first appearance):
Court date (first appearance)
Unknown                440
2023-04-24 00:00:00      2
2005-08-13 00:00:00      1
2012-03-08 00:00:00      1
2018-05-29 00:00:00      1
Name: count, dtype: int64
verdict date:
verdict date
Unknown                471
2018-10-28 00:00:00      1
2018-10-05 00:00:00      1
2016-10-07 00:00:00      1
2016-06-24 00:00:00      1
Name: count, dtype: int64
Verdict:
Verdict
Unknown       469
guilty         24
Guilty         10
Not Guilty      2
Not guilty      1
Name: count, dtype: int64
Years of sentence:
Years of sentence
Unknown            471
awaiting ruling      6
20                   5
10                   4
25                   3
Name: count, dtype: int64
Days to verdict:
Days to verdict
#VALUE!    471
2817         1
2714         1
1939         1
4061         1
Name: count, dtype: int64